--- #YAML:1.0
name: File-Mork
version: 0.1
author:
  - Module-ised by Simon Wistow <simon@thegestalt.org>
  - based on
  - |-
    Created:  3-Mar-2004 by Jamie Zawinski, Anonymous, and Jacob Post.
abstract: an single entry in a mork DB
license: gpl
requires:
  HTML::Entities: 0
  Test::More: 0
dynamic_config: 1
provides:
  File::Mork:
    file: lib/File/Mork.pm
    version: 0.1
  File::Mork::Entry:
    file: lib/File/Mork.pm
    version: 0.1
generated_by: Module::Build version 0.25
